name: Build Images

on:
  push:
    branches: [main, curl-test]
    paths:
      - "Dockerfile"
      - "build.sh"
      - ".github/workflows/build-image.yml" # this file
  
jobs:
  build-images:
    name: ğŸ³ Build Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [amd64]
        architecture: [16.12.0]
    steps:
      - name: ğŸ Checkout repo
        uses: actions/checkout@v2

      - name: ğŸ³ Build Images
        run: |
          docker build --build-arg version=${{ matrix.node-version }} --build-arg ${{ matrix.architecture }} .
          docker images
        working-directory: ./curl-test
